// Generate shape-core's ZIP-3 PREFIX SET from chart-host's ZIP-3 geometry asset.
//
// WHY SHAPE-CORE NEEDS ITS OWN COPY. detectGeo and toGeoIso live in shape-core and run on the
// CLIENT, before any geometry is loaded and without a dependency on chart-host (the dependency
// runs the other way). They need to answer one question - "can this ZIP actually be painted on
// the map we bundle?" - and the only honest source for that answer is the asset's own feature
// ids. So the ids are extracted here, at build time, into a constant.
//
// THE DRIFT THIS CREATES IS THE POINT OF THE TEST BESIDE IT. Two copies of one truth is exactly
// the mirror-drift shape this repo has been bitten by before, so `geoZip3PrefixParity` asserts
// the generated set still equals the asset's ids. Regenerate with
// `node scripts/buildZip3PrefixSet.mjs` whenever the ZIP-3 asset is rebuilt (and re-run
// scripts/cleanZip3Asset.mjs first - it DROPS geometry-less features, and a prefix with no
// geometry must not be in this set either, for the same reason it is dropped there).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ASSET = join(here, "..", "packages", "chart-host", "src", "geoUsZip3.generated.ts");
const OUT = join(here, "..", "packages", "shape-core", "src", "geoUsZip3Prefixes.generated.ts");

const src = readFileSync(ASSET, "utf8");
// The asset is one enormous single-line object literal, so this reads the ids off the text
// rather than parsing ~800KB of geometry to count 896 three-character strings.
const ids = [...src.matchAll(/"id"\s*:\s*"(\d{3})"/g)].map(m => m[1]);
const uniq = [...new Set(ids)].sort();
if (uniq.length < 800) {
    throw new Error(`only ${uniq.length} ZIP-3 ids found in the asset - the format changed, and a `
                  + `short set here would silently mark real ZIPs undrawable`);
}

const packed = uniq.join("");
const body = `// AUTO-GENERATED by scripts/buildZip3PrefixSet.mjs from chart-host's geoUsZip3.generated.ts.
// DO NOT EDIT. Regenerate after rebuilding (and cleaning) the ZIP-3 geometry asset.
//
// The 3-digit ZIP prefixes the bundled ZIP-3 basemap can actually DRAW - ${uniq.length} of the
// 1000 the format allows. The missing ~${1000 - uniq.length} are not an oversight: they are the
// prefixes USPS never assigned to a geographic area, plus the military APO/FPO ranges
// (090-099, 340, 962-966), which are REAL deliverable ZIPs with no place on a map of the
// United States.
//
// WHAT IT IS FOR. A US ZIP used to resolve on its FORMAT alone, so a five-digit string that
// happened to be unmappable was reported as a 100% geo match - and geoMatchPct is a GATE input
// (the server refuses a choropleth under LLMGeoMinMatchPct) and a picker score. A column of
// military ZIPs therefore cleared every geo gate on its way to a map that could not draw a
// single one of them. Membership is tested here so the number the gate reads is the number of
// regions that can actually be painted.
//
// Stored as one packed string of 3-character prefixes: ${packed.length} chars, split once at
// module load. A Set literal of ${uniq.length} quoted strings costs ~6x this in the bundle.
const PACKED =
    ${JSON.stringify(packed)};

/** The 3-digit ZIP prefixes the bundled ZIP-3 basemap carries geometry for. */
export const US_ZIP3_PREFIXES: ReadonlySet<string> = new Set(
    PACKED.match(/.{3}/g) ?? []
);
`;

writeFileSync(OUT, body.replace(/\r?\n/g, "\r\n"), "utf8");
console.log(`wrote ${OUT}`);
console.log(`  ${uniq.length} prefixes, ${packed.length} packed chars`);
console.log(`  first: ${uniq.slice(0, 4).join(",")}  last: ${uniq.slice(-4).join(",")}`);
